export const products = [
  {
    id: 1,
    name: "Basketball",
    price: 15,
    type: "Ball",
    image: "../src/assets/img/1.png",
  },
  {
    id: 2,
    name: "Green Tennis Ball",
    price: 2,
    type: "Ball",
    image: "../src/assets/img/2.png",
  },
  {
    id: 3,
    name: "Badminton Racket",
    price: 100,
    type: "Racket",
    image: "../src/assets/img/3.png",
  },
  {
    id: 4,
    name: "American Football Ball",
    price: 25,
    type: "Ball",
    image: "../src/assets/img/4.png",
  },
  {
    id: 5,
    name: "Football Soccer Ball",
    price: 3100.61,
    type: "Ball",
    image: "../src/assets/img/6.png",
  },
  {
    id: 6,
    name: "Hiking jacket",
    price: 175,
    type: "Clothes",
    image: "../src/assets/img/5.png",
  },
  {
    id: 7,
    name: "Swimming Pool Ball",
    price: 23,
    type: "Ball",
    image: "../src/assets/img/7.png",
  },
  {
    id: 8,
    name: "Ice Skates",
    price: 119,
    type: "Equipment",
    image: "../src/assets/img/8.png",
  },
  {
    id: 9,
    name: "Dumbbells",
    price: 69,
    type: "Dumbbell",
    image: "../src/assets/img/9.png",
  },
  {
    id: 10,
    name: "Skateboard",
    price: 124,
    type: "Skate",
    image: "../src/assets/img/10.png",
  },
];
